# Generated by Django 5.1.3 on 2024-11-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brainTumour", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedImage",
            new_name="brainTumour",
        ),
    ]
