# Generated by Django 5.1.3 on 2024-11-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinCancer', '0002_rename_uploadedimage_skincancer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skinCancer',
        ),
    ]
