# Generated by Django 5.1.3 on 2024-11-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainTumour', '0002_rename_uploadedimage_braintumour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brainTumour',
            new_name='BrainTumourImage',
        ),
    ]
